// <auto-generated />
using System;
using Farkas_Szabolcs_ProiectExamen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farkas_Szabolcs_ProiectExamen.Migrations
{
    [DbContext(typeof(Farkas_Szabolcs_ProiectExamenContext))]
    [Migration("20230115144819_Rezervari")]
    partial class Rezervari
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeCategorie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Magazin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeMagazin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Magazin");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Producator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeProducator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Producator");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MagazinID")
                        .HasColumnType("int");

                    b.Property<long>("NrBuc")
                        .HasColumnType("bigint");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProducatorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Valabilitate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MagazinID");

                    b.HasIndex("ProducatorID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.ProdusCategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("ProdusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("ProdusID");

                    b.ToTable("ProdusCategorie");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Produs", b =>
                {
                    b.HasOne("Farkas_Szabolcs_ProiectExamen.Models.Magazin", "Magazin")
                        .WithMany("Produse")
                        .HasForeignKey("MagazinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farkas_Szabolcs_ProiectExamen.Models.Producator", "Producator")
                        .WithMany("Produse")
                        .HasForeignKey("ProducatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazin");

                    b.Navigation("Producator");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.ProdusCategorie", b =>
                {
                    b.HasOne("Farkas_Szabolcs_ProiectExamen.Models.Categorie", "Categorie")
                        .WithMany("ProdusCategorii")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farkas_Szabolcs_ProiectExamen.Models.Produs", "Produs")
                        .WithMany("ProdusCategorii")
                        .HasForeignKey("ProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Categorie", b =>
                {
                    b.Navigation("ProdusCategorii");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Magazin", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Producator", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Produs", b =>
                {
                    b.Navigation("ProdusCategorii");
                });
#pragma warning restore 612, 618
        }
    }
}
