// <auto-generated />
using System;
using Farkas_Szabolcs_ProiectExamen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farkas_Szabolcs_ProiectExamen.Migrations
{
    [DbContext(typeof(Farkas_Szabolcs_ProiectExamenContext))]
    partial class Farkas_Szabolcs_ProiectExamenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Producator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeProducator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Producator");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NrBuc")
                        .HasColumnType("bigint");

                    b.Property<string>("Origine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pret")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("ProducatorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Valabilitate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProducatorID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Produs", b =>
                {
                    b.HasOne("Farkas_Szabolcs_ProiectExamen.Models.Producator", "Producator")
                        .WithMany("Produse")
                        .HasForeignKey("ProducatorID");

                    b.Navigation("Producator");
                });

            modelBuilder.Entity("Farkas_Szabolcs_ProiectExamen.Models.Producator", b =>
                {
                    b.Navigation("Produse");
                });
#pragma warning restore 612, 618
        }
    }
}
